### ISSUE TITLE
Default title

### ISSUE THREAD

**Issue by CHirch** [Mofeywalker/openmensa-lovelace-card#1]
Hi. I use two Open-Mensa-Sensors and display two cards. It whould be very nice if it is possible to change the title of the card from "OpenMensa" to a default title, e.g. with a configuration like this:
```
   - type: custom:openmensa-card

      entity: sensor.openmensa_sensor

      name: Hauptmensa
```
Thanks a lot for providing this card. I use it every day and it's great!

**Comment by Mofeywalker** [comment]
Hi, I added an option `header` with which you can override the header of the card in #2

**Comment by CHirch** [comment]
Thanks, very nice. It really adds value to the software for me. Great work!
