### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by Vakrehus** [Mofeywalker/openmensa-lovelace-card#3]
pls fix 😢

![image](https://github.com/Mofeywalker/openmensa-lovelace-card/assets/60559245/f6abb89c-fb4e-4f1d-b462-8ecc2215dd7d)

**Comment by Mofeywalker** [comment]
Hi, for me the card and integration work. Have you checked the sensor in the Devloper Tools section of Homeassistant? Does it work?

**Comment by Vakrehus** [comment]
Ohh, I'm editing my brother-in-law's server all the time instead of my own instance. You should always pay attention to the IP address. Sorry for my mistake.
